- name: Remove certificate
  hosts: server
  connection: ssh
  become: true
  become_user: root
  tasks:
      - name: Delete certificate file
        ansible.builtin.file:
            path: "/App/letsencrypt/acme.json"
            state: absent
